### ISSUE TITLE
Clone URL in docs is wrong

### ISSUE THREAD

**Issue by arokem** [singularityware/singularity#12]
The clone URL on this page: 

https://singularityware.github.io/start

is: 

https://github.com/singularityware/singularity/singularity.git

Which seems to have one too many nesting levels. Couldn't find the source of this here, so I thought I would just alert y'all to this. Thanks!

**Comment by vsoch** [comment]
Thanks! The base URL was coming from a variable, which I didn't carefully check (the singularity bit at the end was already there). Fixed.
