### ISSUE TITLE
RFE: Allow hkp keyservers to supply additional information to the user

### ISSUE THREAD

**Issue by ikaneshiro** [singularityware/singularity#6180]
Some hkp key server implementations my want to supply users with additional information upon key submisstion. E.g. have a user verify the identity supplied in a public key via an out of band process. 

This was first proposed by these changes: https://github.com/hpcng/singularity/pull/5464/files/84c11e21820d976499085545a8b789404505f345#diff-89ea8388f9af37fc57250aa45f4d2991ce6c5b7dd4a53b63f543bb4a669dc878R1122 and subsequently pushed out to an RFE in the key server client we use: https://github.com/sylabs/scs-key-client/issues/47

Either approaches should be sufficient in my measurement.

**Comment by DrDaveD** [comment]
Replaced by apptainer/apptainer#20
