### ISSUE TITLE
Failed to open overlay image: can't open for reading, currently in use for writing by another process.

### ISSUE THREAD

**Issue by nikhilweee** [singularityware/singularity#6196]
### Version of Singularity:

```
$ singularity --version
singularity version 3.7.4
```

### Expected behavior

When I run `singularity exec` with an overlay container, I expect it to work.
```
$ singularity exec --overlay /scratch/nv2099/images/overlay-50G-10M.ext3:ro /scratch/work/public/singularity/cuda11.3.0-cudnn8-devel-ubuntu20.04.sif /bin/bash
```

### Actual behavior

However, I get the following error:
```
FATAL:   while loading overlay images: failed to open overlay image /scratch/nv2099/images/overlay-50G-10M.ext3: while locking ext3 partition from /scratch/nv2099/images/overlay-50G-10M.ext3: can't open /scratch/nv2099/images/overlay-50G-10M.ext3 for reading, currently in use for writing by another process
```

### Steps to reproduce this behavior

1. Run `singularity exec` with an overlay file system
2. Kill the singularity process (unclean exit)
3. Try running `singularity exec` again

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
```

### How did you install Singularity

I'm on a cluster, and singularity was preinstalled by the cluster admin.

**Comment by nikhilweee** [comment]
Answering my own question, I managed to solve this quite simply by running:
```
$ fsck.ext3 /scratch/nv2099/images/overlay-50G-10M.ext3
```
Turns out that the previous run of `singularity exec` was somehow killed, leaving the overlay file system in an unclean state.

**Comment by adityamwagh** [comment]
Thanks a lot! @nikhilweee 

PS - What's the chance that a fellow BITSian, who also happens to be at NYU like me, stumbled on the same issue? haha

**Comment by nikhilweee** [comment]
@adityamwagh BITSians for each other, I suppose 🙂

**Comment by tkella47** [comment]
This did not work for me

**Comment by Glosolin** [comment]
I also encountered the same issue, and I tried to clean the overlay file system, but it's not working

**Comment by crotoc** [comment]
I met the same problem. But only on one disk. The solution doesn't work.

I have an overlay, and copy it to a disk, it works as normal. When moving to another disk, I can only use the img in readonly mode, or it says "while locking ext3 partition from ...". So wired.

**Comment by aneekroy** [comment]
fellow NYU student here ...
you need to run :
$ ssh log-3 ps -f -u<net-id>|grep Singu
$ <net-id>   3155561 3147477  0 21:36 pts/1149 00:00:00 Singularity runtime parent

either log-1  or log-2 or log-3 depending upon which log you have used then

$ssh log-3 
.....
$kill  -9  3155561

The process id after your net-id should do the trick if you are stuck with singularity sessions which are not properly closed.

**Comment by crotoc** [comment]
> fellow NYU student here ... you need to run : $ ssh log-3 ps -f -u|grep Singu $ 3155561 3147477 0 21:36 pts/1149 00:00:00 Singularity runtime parent
> 
> either log-1 or log-2 or log-3 depending upon which log you have used then
> 
> $ssh log-3 ..... $kill -9 3155561
> 
> The process id after your net-id should do the trick if you are stuck with singularity sessions which are not properly closed.

Thanks for your reply. What's the meaning of "ssh log-3"? Do you mean when I am connecting to the server I need to add log-3 to my ssh command? Thanks!

**Comment by zhi-dian** [comment]
> fellow NYU student here ... you need to run : $ ssh log-3 ps -f -u|grep Singu $ 3155561 3147477 0 21:36 pts/1149 00:00:00 Singularity runtime parent
> 
> either log-1 or log-2 or log-3 depending upon which log you have used then
> 
> $ssh log-3 ..... $kill -9 3155561
> 
> The process id after your net-id should do the trick if you are stuck with singularity sessions which are not properly closed.

I ran into the same issue, and I found the process that occupied the file. However, that process's id is changing all the time (each time I grep Singularity it will prompt me a new id) and I cannot kill it.

**Comment by DrDaveD** [comment]
This repository is closed.  If you would like help with your issue, please make a new github issue referring back to this one.  If `singularity --version` includes `singularity-ce` make the issue at https://github.com/sylabs/singularity, otherwise make it at https://github.com/apptainer/apptainer.
