### ISSUE TITLE
cannot open directory /.singularity.d: Permission denied

### ISSUE THREAD

**Issue by soichih** [singularityware/singularity#6223]
singularity version 3.7.2 (IU quartz) and 3.6.4 (IU bigred3 and Carbonate)
 
When I run this command.

```
$ singularity exec -e docker://brainlife/pythonvtk:1.1 python3 -c 'import vtk'
```

I run into the following error message.

```
INFO:    Using cached SIF image
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/vtk/vtkCommonCore.py", line 5, in <module>
    from .vtkCommonCorePython import *
ImportError: libvtkWrappingPython34Core-7.0.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/vtk/__init__.py", line 41, in <module>
    from .vtkCommonCore import *
  File "/usr/local/lib/python3.4/site-packages/vtk/vtkCommonCore.py", line 9, in <module>
    from vtkCommonCorePython import *
ImportError: No module named 'vtkCommonCorePython'

```

I am expecting to see this output instead

```
ubuntu@slurm8:~$ singularity exec -e docker://brainlife/pythonvtk:1.1 python3 -c 'import vtk'
INFO:    Using cached SIF image
ubuntu@slurm8:~$ 

```

When I run singularity on IU clusters, it seems that singularity is not able to access /.singularity.d directory

```
$ singularity exec -e docker://brainlife/pythonvtk:1.1 ls /.singularity.d
INFO:    Using cached SIF image
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
/bin/ls: cannot open directory /.singularity.d: Permission denied
```

As far as I know, `/.singularity.d/env` is how the ENV parameters from our docker containers are loaded and we use PATH and LD_LIBRARY_PATH in Dockerfile so our application can find binaries / libraries needed. 

I've had a similar issue a long time ago (https://github.com/hpcng/singularity/issues/4887) and it seems similar but I am not sure why we are having this problem again. Strangely, the problem went away yesterday but re-emerged today. I've asked our administrator if they know anything but I see no configuration/singularity installation changes has occurred since then. I wanted to ping the singularity team to see if anyone could assist us.

Thank you!

**Comment by DrDaveD** [comment]
Hi Soichi.  I think this could be caused by a local configuration setting.  Please check any non-standard settings in singularity.conf.

**Comment by soichih** [comment]
The only thing that I've noticed is this

```
  root default capabilities = no

  mount home = no
  bind path = /etc/localtime
  bind path = /etc/hosts                                         
  bind path = /N/home
  bind path = /N/u
  bind path = /N/soft
  bind path = /N/dcwan
```

The config file hasn't changed since yesterday (and it was working yesterday) so I don't think the configuration setting is to blame? I am not sure..

**Comment by DrDaveD** [comment]
And what are the host operating systems where it is breaking?

**Comment by soichih** [comment]
IU Quartz: RHEL8.4
IU Carbonate: RHEL 7.9
IU Bigred3: Cray Linux Environment (XC40)

I think I've found a possible fix however. On all 3 systems, I was *sharing* the same singularity cache directory (maybe it's a bad idea?) I've updated the config so all 3 systems will use separate `SINGULARITY_CACHEDIR`. Maybe the SIF built on one system is incompatible with others? I thought SIFs are portable across all systems? Testing now.

**Comment by soichih** [comment]
On Bigred3, I had the following in .bashrc

```
export SINGULARITY_TMPDIR=/N/project/brainlife/singularity/tmp
```

I've removed this and cleared the cache again and now it seems to be working fine. I had to add the ENV because the CE on Bigred3 keeps running out of /tmp.. but it looks like singularity has some issue when TMPDIR is set to use lustre filesystem?

**Comment by DrDaveD** [comment]
That's possible.  It certainly wouldn't be recommended in any case since Lustre has so much trouble with lots of small files.  I searched through previous issues and it looks like [you](https://github.com/hpcng/singularity/issues/1052#issuecomment-368059428) may have noticed a related issue a few years ago.

**Comment by soichih** [comment]
Yes, I've opened a ticket about this long time ago. I had an impression that this issue was resolved. It also doesn't explain why I started having this problem now.. I will stay away from using lustre, but local /tmp directory is full on bigred3.. so I don't have too many options at this point. I night need to give up running jobs on bigred3

**Comment by DrDaveD** [comment]
An option for scratch space used by many HPC administrators of machines with diskless nodes is to mount a loopback filesystem on each node from a separate file on the high speed file server.  That uses the best of both worlds, because the data is on the performant file system but the metadata operations are on the nodes.  You might want to try to ask the admins for that.
