### ISSUE TITLE
Fail to pull Docker image on HPC from private GitLab container registry

### ISSUE THREAD

**Issue by florianblume** [singularityware/singularity#6228]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.7.0
```

### Expected behavior

I want to pull a docker image from a private docker registry (Gitlab instance run by my university) from a cluster node of the HPC of my university.

### Actual behavior

Singularity fails with the following message:

```
While making image from oci registry: error fetching image to cache: failed to get checksum for docker://git.tu-berlin.de:5000/florianblume/facial-expression-recognition:latest: error pinging docker registry git.tu-berlin.de:5000: Get "https://git.tu-berlin.de:5000/v2/": Forbidden
```

Pulling images from the official Docker hub works perfectly.

The debug output looks like this:

```
singularity -d pull docker://git.tu-berlin.de:5000/florianblume/facial-expression-recognition:latest
DEBUG   [U=1276305,P=11532]persistentPreRun()            Singularity version: 3.7.0
DEBUG   [U=1276305,P=11532]persistentPreRun()            Parsing configuration file /cluster/singularity/3.7.0/etc/singularity/singularity.conf
DEBUG   [U=1276305,P=11532]handleConfDir()               /home/users/f/florianblume/.singularity already exists. Not creating.
DEBUG   [U=1276305,P=11532]setValue()                    Updated flag 'docker-username' value to: florianblume
DEBUG   [U=1276305,P=11532]getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=1276305,P=11532]parseURI()                    Parsing docker://git.tu-berlin.de:5000/florianblume/facial-expression-recognition:latest into reference
FATAL   [U=1276305,P=11532]pullRun()                     While making image from oci registry: error fetching image to cache: failed to get checksum for docker://git.tu-berlin.de:5000/florianblume/facial-expression-recognition:latest: error pinging docker registry git.tu-berlin.de:5000: Get "https://git.tu-berlin.de:5000/v2/": Forbidden
```

Does that have something to do with the port specification `:5000` in the URL? But it seems to get parsed correctly since only `https://git.tu-berlin.de:5000` is the part that is being pinged. First I thought it's because `ping` is only usable by `root` but that's not true, I can use it without root privileges.

Or is it the `v2` part appended to the URL? I tried to understand in the `go` files what might have happened but I didn't understand where to look from [this line one](https://github.com/hpcng/singularity/blob/c796b1a03fda003a4b0c0c18504e04595759b89f/internal/pkg/build/oci/oci.go#L103) since then it branches into 3 possible `conveyers` (arch, busybox, deboostrap) but none of these programs works on the cluster and therefore different error messages would be thrown and I assume it's using some other conveyer that I'm missing.

Any ideas?

### Steps to reproduce this behavior

Difficult to say, maybe that's an issue of having to specify the port `5000` for the docker registry. So I cannot give a detailed recipe how to reproduce this issue.

### What OS/distro are you running

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

### How did you install Singularity

I didn't, I'm only loading it as a module. It has been installed by the HPC maintainers.

**Comment by DrDaveD** [comment]
I think the key part of the message is the last word: "Forbidden".  Does singularity have permission to read from that URL?

**Comment by florianblume** [comment]
Hi, thanks for your reply! I'm not sure why but I didn't think about that Singularity doesn't have access to the site. When I put `https://git.tu-berlin.de:5000/v2/` in my browser it gives a 403 error and says `authentication required`. I'm not able to access this URL with any combination of username and password (also tried tokens generated in GitLab).

Could it be that it's not accessible since the Docker registry is attached to my project? That it's only possible for admins to retrieve the whole list of Docker images in GitLab but for me it's only possible for my own project so the URL Singularity tries to access is incorrect?

**Comment by DrDaveD** [comment]
I have no idea; you'll need to work with the administrator of the server.

Closing this since the issue is not with singularity itself.  Reopen if you still have trouble after you're able to authenticate.
