### ISSUE TITLE
debian build fails on ubuntu 20.04, mising seccomp and cryptsetup support

### ISSUE THREAD

**Issue by skluth** [singularityware/singularity#6236]
### Version of Singularity:

3.8.3

### Expected behavior

build on ubuntu 20.04 with debuild
build with seccomp and cryptsetup support

### Actual behavior

fails due to missing dependency on golang-go (>= 2:1.13) but golang-go (2:1.13~1ubuntu2) is installed.
Reason is failing version comparison, because  2:1.13 > 2:1.13~1ubuntu2. 
seccomp and cryptsetup not detected since missing in debian/control Build-Depends

### Steps to reproduce this behavior

follow the instructions here for debian build on ubuntu 20.04 

### What OS/distro are you running

ubuntu 20.04

### How did you install Singularity

it is about build

Tested fix: 

modify debian/control like this

Build-Depends:
...
 golang-go (>= 2:1.13~~),
 libseccomp-dev,
 cryptsetup
...

With  libseccomp-dev and cryptsetup installed the debuild works fine. The version comparison 2:1.13~~ < 2:1.13~1ubuntu2) now yields the expected result on ubuntu 20.04.

**Comment by DrDaveD** [comment]
@Kunzol Please look at this.

**Comment by Kunzol** [comment]
# Dependencies
I checked it and found another Build-dependency missing: "devscripts" is needed for the `debchange` command.

I could not see a difference with "libseccomp-dev" installed. 
Additional thoughts about "libseccomp": 
-  there is an option to build without "libseccomp" support and adding the library to dependency it would make it harder to build if libseccomp could not be installed (why ever). 
- I assume, somebody who really needs the libseccomp feature should add it manually. But there should be a note in the `DEBIAN_PACKAGE.md` file.

# Summary: 
-  correct golang-go dependency version
- add devscripts dependency
- add cryptsetup dependency
- add a note about "libseccomp" to `DEBIAN_PACKAGE.md`

# Challange: 
Newer version than v3.8.3 needs "Go compiler (at least version 1.16)", which is not in the Ubuntu 20.04 (golang-go 2:1.13\~1ubuntu2) repository and not in Debian Bullseye (golang-go 2:1.15~1). Should the golang-go 1.16 dependency be added to the master branch to make clear it is not possible to create a package from the master branch?

I don't know, if it is possible to add the changes in git to the tag v3.8.3. And for newer (master) version the dependency should be updated accordingly. Should I add this to branch "release-3.8" ?

Could somebody assist on how to proceed adding the changes to tag v3.8.3 only?

**Comment by DrDaveD** [comment]
@Kunzol We are planning a 3.8.4 early next week, it would be great if you could get this into the release-3.8 branch very soon and we can include it in that tag.   Attn: @kmuriki 

For the master branch, there's a patch down in dist/rpm that makes compiling with 2.15 work.  I expect it would work with 2.13 as well.  Please try applying that from the debian packaging.

**Comment by DrDaveD** [comment]
There should also be a CI test for the Debian packaging so this type of problem doesn't happen again.  There's already #6030 requesting that but nobody has worked on it yet.

**Comment by Kunzol** [comment]
I am not a pro with git, but I will try my best and learn as fast as I can. Maybe I need some help, let's see.

**Comment by DrDaveD** [comment]
Speak up if you need help.  We would like this in the next day or two so we can release 3.8.4.

**Comment by skluth** [comment]
I would like to make a case for seccomp support, which is added by adding "libseccomp-dev"  to the builddeps. The configure step of the build tests for presence of libseccomp and turns on seccomp support if the test is successful. 

Seccomp support is essential to work with e.g. `singularity build --fakeroot ...`. W/o seccomp support --fakeroot is useless.

Why should libseccomp be difficult to install? I am not aware of license problems or disappearing support which could kick it out of debian.

**Comment by DrDaveD** [comment]
I don't agree that seccomp is required for --fakeroot, but on the other hand it should be easy to include as a debian requirement.

--fakeroot can be used with completely unprivileged singularity, if newuidmap/newgidmap is installed, and seccomp shouldn't be needed then.  Privileged singularity --fakeroot pretty much only replaces those two small setuid programs, I believe.

@skluth would you like to submit the pull request instead?

**Comment by skluth** [comment]
In our setup (opensuse tumbleweed) we had singularity w/o seccomp (it was built like that before I filed a bug report on OBS) and the newuidmap/newgidmap stuff installed. Any attempts to build a container with --fakeroot didn't get very far. 

I can try to do the pull request later today (I haven't done this for this project so far, so if I get stuck I let you know).

**Comment by skluth** [comment]
With master I can't build due to go >=1.16 on ubuntu 20.04 ... I try with 3.8.3 and then pull request

**Comment by DrDaveD** [comment]
Right, as I mentioned above, have the debian packaging apply the patch from the dist/rpm directory to work with older go.

**Comment by Kunzol** [comment]
I tried my best with the pull request.

**Comment by kmuriki** [comment]
Thank you for your contributions. This issue will be closed now.
