### ISSUE TITLE
Apply patch for older go in debian packaging

### ISSUE THREAD

**Issue by DrDaveD** [singularityware/singularity#6259]
The master branch now requires go 1.16, but Debian 11 only has go 1.15 available.  Apply the patch from `dist/rpm/go115.patch` in the debian packaging build step if the go version in $PATH is older than 1.16, just like the rpm packaging does.

This will be needed before #6030 can be done.

@skluth or @Kunzol, can you volunteer to do this?

**Comment by skluth** [comment]
I can try ... but I don't understand the `go115.patch` logic ... the patched file is not in the source tree, since it comes from a go module.

**Comment by DrDaveD** [comment]
That's true, it is in the "vendor" subdirectory along with all included modules, which are put into release tarballs.  Those are created with `make -C builddir dist`.   I see [that command](https://github.com/hpcng/singularity/blob/master/mlocal/frags/Makefile.stub#L33) does `go mod vendor` to create the vendor subdirectory.   It appears that the debian packaging isn't currently based on a tarball, so maybe it would work to just run `go mod vendor` and then apply the patch.

**Comment by DrDaveD** [comment]
Continue discussion in apptainer/apptainer#17
