### ISSUE TITLE
refactor "defer" inside of loops

### ISSUE THREAD

**Issue by PaulCharlton** [singularityware/singularity#6266]
refactor "defer" inside of loops - to remove potential/actual resource leaks

=================

this condition is detected by the go linter
1) defer -- defers until the function enclosing the loop exits, which generally means that resources are held until the loop exits.
2) many for loops with defer are never intended to exit until "end of input" condition is reached.
3) resource leaks result while "end of input" is not reached

### Expected behavior

Resources are bound to the nearest local scope, and deferred actions execute within the context of an enclosing loop

**Comment by PaulCharlton** [comment]
PR forthcoming

**Comment by DrDaveD** [comment]
Are these linter messages already coming out but we were ignoring them, or did you reconfigure the linter somehow?

**Comment by kmuriki** [comment]
Thank you for your contributions. This will be closed now.
