### ISSUE TITLE
inspect all "unhandled error" and clean up appropriately

### ISSUE THREAD

**Issue by PaulCharlton** [singularityware/singularity#6270]
there are numerous unhandled error returns throughout the entire code-base.

update those code points to either (1) return/report an error, or (2) syntactically eat them with "_ = func()" instead of "func()"

**Comment by kmuriki** [comment]
Pending issues from the old repo are moved to the new repo (https://github.com/apptainer/apptainer/issues/1391) and cleaned from the old, retired repo
