### ISSUE TITLE
Using --contain changes default pwd

### ISSUE THREAD

**Issue by luator** [singularityware/singularity#6286]
### Version of Singularity:

```
singularity version 3.8.3
```

### Expected behavior

When running `singularity exec` (same for `shell` or `run`), it is normally executed in the current working directory (which is automatically bound into the container).  I would expect that setting `--contain` does not change this behaviour, as long as `$(pwd)` is bound.

### Actual behavior

When using `--contain`, the default pwd changes to the home directory, even if the directory from which it was called is explicitly bound into the container.

I know by now that I can explicitly specify the pwd with `--pwd`, so this is not a critical issue.  I still find it counter-intuitive, though, so I thought it is worth bringing it up.

### Steps to reproduce this behavior

```
$ cd /tmp  # or any other directory != $HOME
$ singularity exec library://alpine pwd
/tmp

$ singularity exec --contain --bind=$(pwd) library://alpine pwd
/home/luator     <-- I would expect this to /tmp as well
```

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

### How did you install Singularity

Build from source.

**Comment by DrDaveD** [comment]
The --contain command is intended for having an environment isolated from the host, so it is not clear to me that it would make sense to have it preserve the current working directory.  In most cases it probably would not be able to.

**Comment by luator** [comment]
For me, it is a common use-case to run things in Singularity that are supposed to operate on the current working directory, e.g. because it executes or processes some files there.  In some of these cases, I need `--contain` (together with `--bind=$(pwd)` to avoid any undesired interference with the host system.
For this use-case, it would be convenient (and in my opinion more consistent behaviour) if pwd would be preserved if it is bound.  But I see that this is something where opinions may differ, so I'm good with closing this, if you prefer the current behaviour.

**Comment by DrDaveD** [comment]
It would be an incompatible change and probably break assumptions that other people have in their scripts so it's probably better to leave it as-is.
