### ISSUE TITLE
update test case which is returning a false negative condition

### ISSUE THREAD

**Issue by PaulCharlton** [singularityware/singularity#6294]
update test case which is returning a false negative condition in `pkg/util/unix/socket_test.go`

```go
		// close socket implies to delete file automatically
		os.Chdir(dir)
		ln.Close()

		// socket file is deleted by net package at close
		if err := os.Remove(path); err == nil {
			t.Errorf("unexpected success during socket removal")
		}
```

note that os.Remove should succeed if the directory is empty

per https://pkg.go.dev/net#TCPListener.File, closing the listener is separate from closing/deleting the file

**Comment by kmuriki** [comment]
Thank you for your contributions. This is closed now.
