### ISSUE TITLE
Singularity Ignores --nohttps if used with oras:// 

### ISSUE THREAD

**Issue by mfarooq-tech** [singularityware/singularity#6302]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.7.1-1
```

### Expected behavior

When oras:// URI is used in combination with `--nohttps (or --no-https)`, singularity should honor the insecure registry mirrors configured in  `/etc/containers/registries.conf`

### Actual behavior

Singularity ignores `--nohttps (or --no-https)` when used with oras:// URI and doesn't honor the insecure registry mirrors configured in  `/etc/containers/registries.conf`

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"


```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by jim3ma** [comment]
For more configurable, when pull image with oras://, singularity should call [github.com/containerd/containerd /remotes/docker/config.ConfigureHosts()](https://github.com/containerd/containerd/blob/main/remotes/docker/config/hosts.go#L73) to load config.

**Comment by jim3ma** [comment]
@mohafarooq /etc/containers/registries.conf is used for docker://, not oras://, the code base to pull images is different between docker:// and oras://. Maybe we can merge the code base to the same one?

**Comment by mfarooq-tech** [comment]
So two issues or behavior inconsistencies :

1. Support for `--nohttps or --no-https`  when used with oras:// (it is already supported for docker://)
2. Support for `/etc/containers/registries.conf or hosts.toml` when used with oras:// (registries.conf is already supported for docker://)

cc: @DrDaveD @dtrudg

**Comment by DrDaveD** [comment]
@cclerget @ikaneshiro What do you think?

**Comment by mfarooq-tech** [comment]
Any updates on this?

**Comment by DrDaveD** [comment]
Cedric told me he thinks it would be good to do this for 3.9.0 so I set that milestone.

**Comment by mfarooq-tech** [comment]
Thank you.

**Comment by DrDaveD** [comment]
Continue discussion in apptainer/apptainer#18
