### ISSUE TITLE
can't install Singularity with sudo - must be root

### ISSUE THREAD

**Issue by acurry22** [singularityware/singularity#6319]
### Version of Singularity:

What version of Singularity are you using? Run: 

```
$ singularity --version

 singularity-3.8.4.tar.gz


<!-- please include command-line output in a code block -->

### Expected behavior

What did you expect to see when you do...?

I expected to be able to install Singularity with root user rights.  Our env does not allow su -i (root) only user's with sudo (wheel)

### Actual behavior

What actually happend? Why was it incorrect?

[/opt/singularity-3.8.4 ] $ sudo ./mconfig
[sudo] password for sysadm:
Configuring for project `singularity' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.13)... not found!
mconfig: could not complete configuration



<!-- if this is a feature request, you can ignore this next part -->

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

cd /singularity
sudo ./mconfig

### What OS/distro are you running

```
$ cat /etc/os-release

[/opt/singularity-3.8.4 ] $ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

[/opt/singularity-3.8.4 ] $ ll
total 320
drwxr-xr-x.  3 root root     65 Nov 26 06:39 builddir
-rw-r--r--.  1 root root  46017 Nov  9 14:57 CHANGELOG.md
drwxr-xr-x.  7 root root     91 Nov 26 06:20 cmd
-rw-r--r--.  1 root root   8296 Aug 12 01:08 CONTRIBUTING.md
-rw-r--r--.  1 root root   4308 Aug 16 12:43 CONTRIBUTORS.md
-rw-r--r--.  1 root root    343 May 21  2021 COPYRIGHT.md
drwxr-xr-x.  4 root root     31 Nov 26 06:20 dist
drwxr-xr-x.  5 root root    125 Nov 26 06:20 docs
drwxr-xr-x. 31 root root   4096 Nov 26 06:20 e2e
drwxr-xr-x.  5 root root    218 Nov 26 06:20 etc
drwxr-xr-x. 23 root root   4096 Nov 26 06:20 examples
-rw-r--r--.  1 root root   3131 Nov  9 10:06 go.mod
-rw-r--r--.  1 root root 144745 Nov  9 10:06 go.sum
-rw-r--r--.  1 root root   5208 Nov  9 14:57 INSTALL.md
drwxr-xr-x.  4 root root     28 Nov 26 06:20 internal
-rw-r--r--.  1 root root  11358 May 21  2021 LICENSE-APACHE-2.0
-rw-r--r--.  1 root root   2151 May 21  2021 LICENSE-LBNL.md
-rw-r--r--.  1 root root   1722 Aug 12 01:08 LICENSE.md
drwxr-xr-x.  3 root root    122 Nov 26 06:20 makeit
-rwxr-xr-x.  1 root root  25618 Aug 16 12:43 mconfig
drwxr-xr-x.  5 root root     48 Nov 26 06:20 mlocal
-rw-r--r--.  1 root root    384 May 21  2021 NOTICE-APACHE-2.0
drwxr-xr-x. 15 root root    191 Nov 26 06:20 pkg
-rw-r--r--.  1 root root   2814 Aug 16 12:43 README.md
-rw-r--r--.  1 root root   4424 Aug 16 12:43 RELEASE_PROCEDURE.md
drwxr-xr-x.  2 root root    286 Nov 26 06:20 scripts
-rw-r--r--.  1 root root   5061 Nov  9 14:58 singularity.spec
-rw-r--r--.  1 root root   4555 Aug 12 01:08 SUPPORT.md
drwxr-xr-x. 12 root root    219 Nov  9 15:01 vendor
-rw-r--r--.  1 root root      6 Nov  9 15:01 VERSION
[/opt/singularity-3.8.4 ] $ pwd
/opt/singularity-3.8.4
[/opt/singularity-3.8.4 ] $ sudo ./mconfig
Configuring for project `singularity' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.13)... not found!
mconfig: could not complete configuration
[/opt/singularity-3.8.4 ] $

GO IS INSTALLED and WORKING :)

[~/code/go ] $ echo $GOPATH
/home/sysadm/code/go
[~/code/go ] $ echo $PATH
/usr/local/go/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/go/bin:/home/sysadm/.local/bin:/home/sysadm/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin:/home/sysadm/code/go
[~/code/go ] $ go version
go version go1.17.3 linux/amd64
[~/code/go ] $ ll /home/sysadm/code/go
total 4
-rw-rw-r--. 1 sysadm sysadm 123 Nov 17 17:26 best.go
drwxr-xr-x. 2 root   root     6 Nov 26 06:49 bin
drwxrwxr-x. 3 sysadm sysadm  17 Nov 17 17:26 pkg
drwxrwxr-x. 2 sysadm sysadm   6 Nov 17 17:22 src
[~/code/go ] $ go run /home/sysadm/code/go/b
best.go  bin/
[~/code/go ] $ go run /home/sysadm/code/go/b
best.go  bin/
[~/code/go ] $ go run /home/sysadm/code/go/best.go
YOU ARE THE BEST!
[~/code/go ] $ cat /home/sysadm/code/go/best.go
        package main

        import "fmt"

        func main() {
            fmt.Println("YOU ARE THE BEST!")
        }
[~/code/go ] $

**Comment by DrDaveD** [comment]
sudo does not preserve the PATH when it executes commands because that is not secure.

My first recommendation is to not do the compile with sudo, but instead leave those files owned by an unprivileged user.  Then only use sudo when you do the install command.

If you really don't want to do it that way, you'll be better off doing `sudo -s` to start a shell, and then set up the environment the way you want it before doing the compilation commands.

**Comment by acurry22** [comment]
I ended up finding and installing singularly rpm with yum.

Is there anything else I need to install besides that ram to get up and
running with singularly?

Confused on why documentation references docker, such as in singularity
environment when docker is not required.  Is there user guide for rpm and
getting up and running with no internet access from the VM?

I've never used singularly and want to setup PBS for HPC.

Anna

**Comment by DrDaveD** [comment]
> Is there anything else I need to install besides that ram to get up and running with singularly?

Nothing else should be needed.

> Confused on why documentation references docker, such as in singularity environment when docker is not required.

Singularity is able to use docker containers, which many people find convenient.

> Is there user guide for rpm and getting up and running with no internet access from the VM?

Not that I know of.

Closing since the original problem is solved by using yum.
