### ISSUE TITLE
How to dynamically set PS1 through bashrc?

### ISSUE THREAD

**Issue by nikhilweee** [singularityware/singularity#6320]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
singularity version 3.7.4
```

### Expected behavior

I have miniconda installed in a singularity container. As soon as I launch my container, I expect the prompt to show the current conda environment as a prefix. I have the following lines in `~/.bashrc`
```bash
SINGULARITYENV_PS1='\u at \h on singularity \w $'

# If inside singularity, use conda from the image.
# The /ext3 directory is only available on singularity.
if [ -f /ext3/miniconda3/etc/profile.d/conda.sh ]; then
   source /ext3/miniconda3/etc/profile.d/conda.sh
   conda activate base
   # For some reason PS1 isn't updated. 

    # <Tried inserting a bunch of things here, none of them worked>

   # Fine, I give up. Notify instead.
   echo "current conda environment: ${CONDA_DEFAULT_ENV-base}"
# Else, load the local conda environment.
elif [ -f /opt/conda/etc/profile.d/conda.sh ]; then
   source /opt/conda/etc/profile.d/conda.sh
   conda activate base
fi
```

### Actual behavior

The singularity prompt successfully changes to `\u at \h on singularity \w $`, but it doesn't show the active conda env.

### Things I tried
1. I tried adding `echo $PS1` right after `conda activate base`. This prints out the correct prompt with the currently active environment modifier `(base)`, but unfortunately the prompt on the container still doesn't change.
2. I tried adding `SINGULARITYENV_PS1=$CONDA_PROMPT_MODIFIER$PS1` right after `conda activate base`. Again, this has no effect. I can confirm that `$CONDA_PROMPT_MODIFIER` contains the correct modifier, so that's not the issue.

### Steps to reproduce this behavior

Launch a singularity container having an active installation of anaconda/miniconda, and add the line `source /ext3/miniconda3/etc/profile.d/conda.sh` to `bashrc` (assuming that's where you installed conda).

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"
```

### How did you install Singularity

I'm using singularity on a cluster, so I'm not sure how the admin installed it.

**Comment by nikhilweee** [comment]
One hack that works for me right now is the following:
```bash
# Default environment to activate on singularity
singcondaenv=base

# If inside singularity, use conda from the image.
# The /ext3 directory is only available on singularity.
if [ -f /ext3/miniconda3/etc/profile.d/conda.sh ]; then
   source /ext3/miniconda3/etc/profile.d/conda.sh
   conda activate $singcondaenv
# Else, load the local conda environment.
elif [ -f /opt/conda/etc/profile.d/conda.sh ]; then
   source /opt/conda/etc/profile.d/conda.sh
   conda activate base
fi

# Hack: add $singcondaenv to the prompt manually
SINGULARITYENV_PS1='($singcondaenv) \u at \h on singularity \w $'

```
We're setting PS1 even before the environment is getting activated. That's BAD.
A more elegant solution would be much appreciated.

**Comment by DrDaveD** [comment]
I don't have a more elegant solution, sorry.  You might have better luck asking the whole community on the mailing list or slack.
