### ISSUE TITLE
Cannot install miniconda inside singularity container on WSL

### ISSUE THREAD

**Issue by andrearosasco** [singularityware/singularity#6340]
What version of Singularity are you using? Run:

```
$ singularity version 3.5.3
``` 
I'm trying to create a sandbox and to install miniconda inside of it with the following commands:
```
singularity build --fakeroot --sandbox sandboxes/example-sandbox docker://nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
singularity shell --writable --fakeroot sandboxes/example-sandbox/

apt update
apt-get install -y vim curl wget unzip locales software-properties-common

wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh -O /opt/miniconda.sh
bash /opt/miniconda.sh -b -p /opt/miniconda
```

I'd expect it to correctly install conda, instead I get:
```
Traceback (most recent call last):
  File "entry_point.py", line 59, in <module>
  File "concurrent/futures/process.py", line 555, in __init__
  File "concurrent/futures/process.py", line 165, in __init__
  File "multiprocessing/queues.py", line 42, in __init__
  File "multiprocessing/context.py", line 68, in Lock
  File "multiprocessing/synchronize.py", line 162, in __init__
  File "multiprocessing/synchronize.py", line 57, in __init__
OSError: [Errno 30] Read-only file system
[27756] Failed to execute script entry_point
```

Why isn't fakeroot enough permission to install it?
I've also tried to enter the container with:
```
sudo su
singularity shell --writable sandboxes/example-sandbox/
```
but I get the same result.

I read that this might be an issue with `/dev/shm` and `/run/shm` and as a matter of fact they seem to be two links pointing at each other (not good I guess).

Also, I'm not sure if this is part of the problem but every time I log into the sandbox I get
`WARNING: Skipping mount /home/[username]/hpc [cwd]: /home/[username]/hpc doesn't exist in container`
but I thought the home directory should get mounted automatically.

**Comment by DrDaveD** [comment]
Clearly fakeroot is enough to make it writable, because the 'apt' command works.

I don't know why you're getting that error.  I ran your same steps on my test machine and it succeeded.  I suggest that you try running it with strace.

The problem regarding the home directory is that with --writable singularity will not create any bind mount points.  You can do the mkdir yourself under the example-sandbox directory first.

**Comment by andrearosasco** [comment]
Actually for some reason, just to install `strace`, I had to start the container with:
```
sudo su
singularity shell --writable sandboxes/example-sandbox/
```
since entering just with `--fakeroot` and trying to install it was giving these errors:
```
W: chown to _apt:root of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
W: chmod 0700 of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
W: chown to _apt:root of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (1: Operation not permitted)
W: chmod 0700 of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (1: Operation not permitted)
Do you want to continue? [Y/n]
Err:1 http://archive.ubuntu.com/ubuntu focal/main amd64 libunwind8 amd64 1.2.1-9build1
  Could not open file /var/cache/apt/archives/partial/libunwind8_1.2.1-9build1_amd64.deb - open (13: Permission denied) [IP: 91.189.88.152 80]
Err:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 strace amd64 5.5-3ubuntu1
  Could not open file /var/cache/apt/archives/partial/strace_5.5-3ubuntu1_amd64.deb - open (13: Permission denied) [IP: 91.189.88.142 80]
W: Download is performed unsandboxed as root as file '/var/cache/apt/archives/partial/libunwind8_1.2.1-9build1_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/archives/partial/libunwind8_1.2.1-9build1_amd64.deb - PrepareFiles (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/archives/partial/strace_5.5-3ubuntu1_amd64.deb - PrepareFiles (13: Permission denied)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libu/libunwind/libunwind8_1.2.1-9build1_amd64.deb  Could not open file /var/cache/apt/archives/partial/libunwind8_1.2.1-9build1_amd64.deb - open (13: Permission denied) [IP: 91.189.88.152 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/strace/strace_5.5-3ubuntu1_amd64.deb  Could not open file /var/cache/apt/archives/partial/strace_5.5-3ubuntu1_amd64.deb - open (13: Permission denied) [IP: 91.189.88.142 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
Anyway, I ran the command with strace but I still can't figure out what is the problem. This is strace output:
[strace.txt](https://github.com/apptainer/singularity/files/7689075/strace.txt)

**Comment by DrDaveD** [comment]
Did you still get the same error under strace?  If so, I suggest running it again with `-f -s1024` options, so we can see child processes and complete messages.

**Comment by andrearosasco** [comment]
In the end I solved it by compiling part of the image on the remote builder.
I think it's a problem specific to the WSL tho

**Comment by DrDaveD** [comment]
What is WSL?

**Comment by andrearosasco** [comment]
It's a way to run Linux on Windows. [Here](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) there is more info on how it works

**Comment by DrDaveD** [comment]
Oh right, I knew it sounded familiar.  Ok, I'll go ahead and close this since you have a workaround.
