### ISSUE TITLE
kernel dmesg log overflow with new version

### ISSUE THREAD

**Issue by idesk2596** [singularityware/singularity#6344]
### Version of Singularity:

What version of Singularity are you using? Run:

```
3.9.1
```

Hi,

I have upgrade the kernel to 5.15.5 (Ubuntu 18.04) and starting to see below
prints in kernel log in each execution flooding the log..

```
...
loop1: detected capacity change from 0 to 1153056
loop1: detected capacity change from 1153056 to 1152984
overlayfs: "xino" feature enabled using 3 upper inode bits.
loop1: detected capacity change from 0 to 1153056
loop1: detected capacity change from 1153056 to 1152984
overlayfs: "xino" feature enabled using 3 upper inode bits.
loop1: detected capacity change from 0 to 1059808
loop1: detected capacity change from 1059808 to 1059736
overlayfs: "xino" feature enabled using 3 upper inode bits.
loop1: detected capacity change from 0 to 1059808
loop1: detected capacity change from 1059808 to 1059736
overlayfs: "xino" feature enabled using 3 upper inode bits.
..
```

The ```loop1: detected capacity change from``` prints when running SIF images only, nothing printed if sandbox. (squashfs?)
and ```overlayfs: "xino" feature enabled using 3 upper inode bits``` stops if ```enable overlay = no```
or if it is enabled and the overlay module option disabled:
 ```echo 'options overlay xino_auto=off' > /etc/modprobe.d/overlay.conf``` but not sure if this is desirable..

**Comment by DrDaveD** [comment]
With version 3.9.x you must be using singularity-ce (see singularity --version) so please report this instead to https://github.com/sylabs/singularity.
