### ISSUE TITLE
singularity: symbol lookup error: singularity: undefined symbol: seccomp_api_get | Ubuntu 18.04 

### ISSUE THREAD

**Issue by chaseschuette** [singularityware/singularity#6346]
### Version of Singularity: 3.9.2

What version of Singularity are you using? Run:

```
$ singularity --version
singularity-ce version 3.9.2
```

### Expected behavior

What did you expect to see when you do...?
Using OpenPBS to submit a job that executes the command (a simplified version):
```
singularity exec container.squashfs echo "hello"
```
I would expect hello to be printed in the output file

### Actual behavior

What actually happend? Why was it incorrect?

Printed in the output file:
```
singularity: symbol lookup error: singularity: undefined symbol: seccomp_api_get
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
Ubuntu 18.04.1 LTS (Bionic Beaver)

```

### How did you install Singularity
Followed install steps in sylabs admin install guide using tarball. Used 
```
mconfig --prefix=/apps/singularity/3.9.2
```
Write here how you installed Singularity. Eg. RPM, source.
Downloaded 3.9.2 tarball, built and installed into /apps/singularity/3.9.2

**Comment by DrDaveD** [comment]
This is singularity-ce, please submit your report to https://github.com/sylabs/singularity.
