### ISSUE TITLE
ERROR  : Failed to open current working directory: Permission denied

### ISSUE THREAD

**Issue by Arjun-D7** [singularityware/singularity#6347]
Hi All,

i am getting permission denied error whenever i am trying to load the singularity module through sudo, if an user tries to load the singularity module through sudo we will get permission denied, we have granted the permissions in sudoers to execute the singularity commands 

if we set the users home directory permissions to 705 '/home/user' it will work without any issues but if we set the users   home directory permissions to 700 we will get the below error 

in our case drivelog-reader is a service account this service account home directory we can keep the tight permissions but the AD users who will tries to sudo to this service account should be relaxed with 705 then only it will work 

can you suggest how we can fix this issue when we keep the users home directory to 700  

What version of Singularity are you using? Run:
singularity version 3.8.0

### Expected behavior

What did you expect to see when you do...?
$ sudo -u drivelog-reader /shared/apps/rhel/singularity/bin/singularity run docker://ubuntu
INFO:    Using cached SIF image
Singularity>
Singularity>
Singularity>

### Actual behavior

What actually happend? Why was it incorrect?

$ sudo -u drivelog-reader /shared/apps/rhel/singularity/bin/singularity run docker://ubuntu
INFO:    Using cached SIF image
WARNING: can't determine current working directory: stat .: permission denied
WARNING: can't determine current working directory
ERROR  : Failed to open current working directory: Permission denied

How can others reproduce this issue/problem?

try running singularity module with sudo option 
sudo -u drivelog-reader /shared/apps/rhel/singularity/bin/singularity run docker://ubuntu

### What OS/distro are you running

# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"

### How did you install Singularity

i have loaded Singularity through module command

# module avail
---------------------------------------------------------------- /shared/modules/rhel ----------------------------------------------------------------
crun/1.2.31  git/2.27.1  go/1.17.2  podman/4.0.0  python/3.8.5  python/3.9.0  singularity/3.8.0

----------------------------------------------------------- /usr/local/Modules/modulefiles -----------------------------------------------------------
dot  module-git  module-info  modules  null  use.own

Key:
loaded  modulepath
# module load singularity/3.8.0
# module list
Currently Loaded Modulefiles:
 1) singularity/3.8.0
[root@SE01Z99GERRIT01 ~]#

**Comment by DrDaveD** [comment]
First, we're asking that new issues be created on https://github.com/apptainer/apptainer instead of here.

Next, we don't have the module command so you'd have to back up and give instructions that anybody can use to duplicate.

Finally, this seems to be more likely an issue with your local environment than with singularity.  My guess is that you're attempting to execute the command from a directory not accessible to the drivelog-reader account.   I'll close this issue, and if you still need help, open a new apptainer issue.
