### ISSUE TITLE
Incorrect instructions for checking out tag in INSTALL.md 

### ISSUE THREAD

**Issue by slash5toaster** [singularityware/singularity#6349]
The method of checking out a tag in the install.md is incorrect.  The instruction `git checkout v3.8.5` puts users on new branch of master and not on the tag.  
The correct way to get a tag is `git checkout tags/v3.8.5` for a detached head or `git checkout -b v3.8.5 tags/v3.8.5`

You have to reference `tags/<tag name>` to get to a tag. 

### Version of Singularity:

What version of Singularity are you using? Run:

3.8.5

### Expected behavior
Expect to be on the tag branch and not the master. 
What did you expect to see when you do...?

``` 
~ $ git clone https://github.com/apptainer/singularity.git $TMP/singularity-good/
Cloning into '/scratch/singularity-good'...
remote: Enumerating objects: 98605, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 98605 (delta 0), reused 0 (delta 0), pack-reused 98601
Receiving objects: 100% (98605/98605), 35.49 MiB | 43.53 MiB/s, done.
Resolving deltas: 100% (63004/63004), done.

~ $ cd $TMP/singularity-good/
singularity-good $ git diff --shortstat master..tags/v3.8.5
 424 files changed, 8235 insertions(+), 12618 deletions(-)

singularity-good $ git checkout -b v3.8.5 tags/v3.8.5
Switched to a new branch 'v3.8.5'

singularity-good $ git diff --shortstat master
 424 files changed, 8235 insertions(+), 12618 deletions(-)
```

### Actual behavior

What actually happened? Why was it incorrect?
Note there is no difference between the master and the new branch when doing a git diff. 

```
$ git clone https://github.com/apptainer/singularity.git $TMP/singularity-bad/
Cloning into '/scratch/singularity-bad'...
remote: Enumerating objects: 98605, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 98605 (delta 0), reused 0 (delta 0), pack-reused 98601
Receiving objects: 100% (98605/98605), 35.49 MiB | 42.36 MiB/s, done.
Resolving deltas: 100% (63004/63004), done.

$ cd $TMP/singularity-bad/
singularity-bad $ git diff --shortstat master..tags/v3.8.5
 424 files changed, 8235 insertions(+), 12618 deletions(-)

singularity-bad $ git checkout -b v3.8.5
Switched to a new branch 'v3.8.5'

singularity-bad $ git diff --shortstat master
$

singularity-bad $ git diff --shortstat tags/v3.8.5
 424 files changed, 12618 insertions(+), 8235 deletions(-)

```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
a *fresh* git clone of the repository.  using an existing repo may mask the problem

### What OS/distro are you running

n/a

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.
source

**Comment by DrDaveD** [comment]
The error is that you didn't follow the instruction in INSTALL.md which says to do
```
git checkout v3.8.5
```
You instead did
```
git checkout -b v3.8.5
```
which says to create a new branch called v3.8.5 from the current branch, it doesn't say to checkout the v3.8.5 tag.  The instruction in INSTALL.md is correct.
