### ISSUE TITLE
"WARNING: incompatible SIF version" and "WARNING: Skipping container verification"

### ISSUE THREAD

**Issue by ZisongXu** [singularityware/singularity#6354]
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity --version
3.9.2
```

When I run:
$ singularity pull --arch amd64 library://library/default/ubuntu:16.04
$ singularity run ubuntu_16.04.sif 
### Expected behavior

What did you expect to see when you do...?

No warning and I can run the containers ubuntu_16.04.sif

### Actual behavior

What actually happend? Why was it incorrect?

WARNING: incompatible SIF version
WARNING: Skipping container verification

FATAL:   could not open image /home/zisong/singularity_test/ubuntu_16.04.sif: incompatible SIF version

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

### How did you install Singularity

Write here how you installed Singularity. Eg. RPM, source.

**Comment by DrDaveD** [comment]
Version 3.9.2 is Sylabs' version, so please instead report your problem at https://github.com/sylabs/singularity
