### ISSUE TITLE
INFO:    Could not find any nv files on this host! WARNING: passwd file doesn't exist in container, not updating WARNING: group file doesn't exist in container, not updating open /.singularity.d/env: permission denied

### ISSUE THREAD

**Issue by geyang** [singularityware/singularity#6356]
# Not Sure if Cluster Singularity Installation is Faulty

Dear maintainers, we are running into the following error on the LNL supercloud cluster. We are asking the admins to look into this, but we would like to ask you if this is attributable to a faulty Singularity configuration, or there are things we can do in our docker container to get things to work.

### Version of Singularity: 3.8.15

```
$ singularity --version
```
```
singularity version 3.7.2-1
```

### Expected behavior

This is running a basic docker container on LNL Supercloud.

```bash
mkdir -p /state/partition1/user/$USER  

export TMPDIR=/state/partition1/user/$USER  
singularity pull --docker-login docker://alpine 
```

this works fine. And then the following line breaks:

```bash
singularity exec --nv alpine_latest.sif bash -c 'echo "hey"'
```

### Actual behavior

```bash
INFO:    Could not find any nv files on this host!
WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
```

### What OS/distro are you running

```bash
(base) geyang@login-3:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Singularity

Need to ask the admins. The admins said:

> there is a setting in the singularity configuration that prevents folks from making things world-readable that might be responsible for this error. If an image is built somewhere else it could work.

> We don’t allow users to make anything world-readable, whether that be in your home directory or a group directory. When you run a docker pull the files Singularity creates before being packaged into the .sif inherit this setting, which prevents the setting world permission bits on any of the created files. So all the standard OS files in the container don’t have world read or execute permission. When you run in the container you run as a user, and all the files are owned by root, so you get the permission denied error.

**Comment by DrDaveD** [comment]
Please work with the admins to figure this out.  The info message about --nv sounds like there's no nvidia GPU on that host.  `/etc/singularity/nvliblist.conf` has a list of files that singularity looks for.  The other warnings about readonly sounds like they have a local configuration setting on that machine and you'll need to work with them on that.
