### ISSUE TITLE
Flag mistake in docs section the about `--without-suid` build flag

### ISSUE THREAD

**Issue by darkvertex** [singularityware/singularity#6358]
There is what appears to be a mention of a nonexistent build flag in the docs.

The section for "**[Unprivileged (non-setuid) Installation](https://sylabs.io/guides/3.5/admin-guide/installation.html#unprivileged-non-setuid-installation)**" mention a `--without-setuid` flag but apparently in the current version it is called `--without-suid`.

**Comment by DrDaveD** [comment]
Thanks for pointing that out.  It is still in the current userdocs and admindocs.
