### ISSUE TITLE
Enable insecure mode with SSL via registries.conf not working

### ISSUE THREAD

**Issue by hashkeks** [singularityware/singularity#6359]
### Version of Singularity: 

```
$ singularity version
3.8.2
```

### Expected behavior

When editing the config file `/etc/containers/registries.conf` and setting `prefix` to my registry's domain and `insecure` to true, I expected the singularity client to push and pull to/from the selected registry which only serves a self-signed, untrusted certificate.
This approach was done as suggested in this issue: https://github.com/apptainer/singularity/issues/4725

### Actual 'request'
An option like `--skip-verify` (similar to `curl -k` for example) would be good or that the setting `insecure = true` in `/etc/containers/registries.conf` (see https://github.com/apptainer/singularity/issues/4725) would be applied. Is there no way to skip the verification of SSL certificates with singularity?

### Actual behavior

The settings don't do any difference. I still get the 'unknown authority' error message from singularity:
```
FATAL:   Unable to get library client configuration: unable to get library service URI: error making request to server: Get "https://my.domain.com/assets/config/config.prod.json": x509: certificate signed by unknown authority
```

### Steps to reproduce this behavior

Try to push/pull an image to/from a registry that uses a self-signed, untrusted certificate.
I'm aware that I can make this certificate trusted on a system level, but that's not possible in my use case. 

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity

From source.

**Comment by DrDaveD** [comment]
It would be helpful if you supplied the whole command line you use to get that error message.

In any case, please move this issue to https://github.com/apptainer/apptainer as requested at the top of the [README](https://github.com/apptainer/singularity#readme), since this repository is no longer in active development.  It's OK to refer to older singularity versions.

**Comment by hashkeks** [comment]
Hello,
I edited the issue since this also applies to older versions, like 3.8.2.
The command for example are
```
singularity push -U alpine.sif library://username/collection-name/alpine:latest
```

```
singularity pull alpine.sif library://collection-name/alpine:latest
``` 
or
```
singularity remote login
```
Just anything that requires any interaction with the server does not work since the connection is not accepted by the client due to the untrusted certificate.

Edit: This is a screenshot of my `registries.conf`, *.example.com is in reality of course my actual domain name.
![registries](https://user-images.githubusercontent.com/34633191/152124351-aaedb7c8-a5a5-437d-bcb2-09cf48ce72bb.jpg)

**Comment by gregseth** [comment]
I have version 3.9.0 and configured my `~/.config/containers/registries.conf` to allow my internal domain. I have the same problem, but only when I push an image. Pulling from the internal registry with the self signed certificate works fine.

**Comment by DrDaveD** [comment]
@gregseth Since you are using SingularityCE (only they have 3.9.x) I suggest submitting the issue to https://github.com/sylabs/singularity.  This is also an area of the code that their developers wrote so they'd be better at solving it.
