### ISSUE TITLE
Centos bottstrap

### ISSUE THREAD

**Issue by Lcornet** [singularityware/singularity#6361]
### Version of Singularity:

singularity-ce version 3.8.0

### Expected behavior

Build of a container images from mirror url of centos 8.

### Actual behavior

Fail to get the mirror url.

Build target 'OGstranslate.sif' already exists and will be deleted during the build process. Do you want to continue? [N/y] y
INFO:    Starting build...
INFO:    Skipping GPG Key Import
http://mirror.centos.org/centos-8/8/BaseOS/x86_64/os/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
FATAL:   While performing build: conveyor failed to get: while bootstrapping: exit status 1

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Bootstrap: yum
OSVersion: 8
MirrorURL: http://mirror.centos.org/centos-8/8/BaseOS/x86_64/os/
Include: yum

### What OS/distro are you running

VERSION="18.04.6 LTS (Bionic Beaver)"

### How did you install Singularity

From source, but singularity works well it is juste a problem of lentos repo. Could you help me to get a correct MirrorURL:. This lentos was working until yesterday.

**Comment by DrDaveD** [comment]
Since you're using singularity-ce, please report instead to https://github.com/sylabs/singularity.
