### ISSUE TITLE
Can I prevent users from accessing the container filesystem?

### ISSUE THREAD

**Issue by andy-bell101** [singularityware/singularity#6395]
I'm hoping that Singularity can help us obfuscate our source code on our HPC. We develop primarily in Python, and we've had problems with users taking copies of the code and making their own modifications which messes up our V&V procedures. I think what I'm asking is: can Singularity containers or the runtime be configured so that unprivileged users can't access the filesystem inside the container? 

I think the simplest way of ensuring this is to only allow users to use the `run` command, and prevent them using `shell` and `exec` to run arbitrary commands inside the container. Something like this:

```
#> singularity run hello-world-locked-down.sif
Hello world!
#> singularity exec hello-world-locked-down.sif cat ~/some_file.txt
User 'abc' does not have exec privileges for container 'hello-world-locked-down.sif'
#> singularity shell hello-world-locked-down.sif
User 'abc' does not have shell privileges for container 'hello-world-locked-down.sif'
```

I've tried looking through the docs but I can't find a feature like this mentioned anywhere.

### Version of Singularity:

`singularity version 3.8.6`

**Comment by DrDaveD** [comment]
I don't think that's possible but I suggest that you contact the mailing list or slack channel to reach the community.  This forum is more for requesting changes and reporting problems, not asking questions.
